name: Model Development Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest-gpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Git user
        run: |
          git config --global user.email "azizbayupratama46@gmail.com"
          git config --global user.name "azizbp"
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          git clone https://huggingface.co/datasets/garythung/trashnet

      - name: Run Training Script
        run: |
          python train_model.py
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      
      - name: Push Model to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python push_to_hub.py
